context:
  version: "1.13.0"

package:
  name: typespec
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@typespec/compiler/-/compiler-${{ version }}.tgz
  sha256: 69e2809faf5f068968113605f21ec840139dd43c4369a3ae19a877c6aec2c8d9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Describe your data up front and generate schemas, API specifications, client / server code, docs, and more.
  homepage: https://github.com/microsoft/typespec
  repository: https://github.com/microsoft/typespec

extra:
  recipe-maintainers:
    - danielnachun
