context:
  version: "1.17.0"

package:
  name: typespec
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@typespec/compiler/-/compiler-${{ version }}.tgz
  sha256: 6fbd1d4e3640c07e2600ed738ebc274b2cf235a2352fc1de6af55a2995ed2703

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Describe your data up front and generate schemas, API specifications, client / server code, docs, and more.
  homepage: https://github.com/microsoft/typespec
  repository: https://github.com/microsoft/typespec

extra:
  recipe-maintainers:
    - danielnachun
