context:
  version: "1.7.1"

package:
  name: typespec
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@typespec/compiler/-/compiler-${{ version }}.tgz
  sha256: f733b52d72a9ae0e7f22b0e4414eac84ce1c69389d9ae51d8196f3fa21ed2631

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Describe your data up front and generate schemas, API specifications, client / server code, docs, and more.
  homepage: https://github.com/microsoft/typespec
  repository: https://github.com/microsoft/typespec

extra:
  recipe-maintainers:
    - danielnachun
