context:
  version: "0.67.1"

package:
  name: typespec
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@typespec/compiler/-/compiler-${{ version }}.tgz
  sha256: b962f9cbf5c613c7e09bde809a0017ba5674ce66d731334fd8d39af06fb022c3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Describe your data up front and generate schemas, API specifications, client / server code, docs, and more.
  homepage: https://github.com/microsoft/typespec
  repository: https://github.com/microsoft/typespec

extra:
  recipe-maintainers:
    - danielnachun
