context:
  version: "0.65.3"

package:
  name: typespec
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@typespec/compiler/-/compiler-${{ version }}.tgz
  sha256: 859dd34b45f9375ac382c1d8760a11668c4f7555454c5f1ac3678ca6174deaa9

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tsp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Describe your data up front and generate schemas, API specifications, client / server code, docs, and more.
  homepage: https://github.com/microsoft/typespec
  repository: https://github.com/microsoft/typespec

extra:
  recipe-maintainers:
    - danielnachun
